### ISSUE TITLE
How to get addresses and offsets updated

### ISSUE THREAD

**Issue by L1ghtingBolt** [Fish-Sticks/headhunter#3]
How can you get the addresses and offsets using IDA to make it work?

**Comment by ThatPhoenix** [comment]
pain

**Comment by Fish-Sticks** [comment]
IDA, cheat engine, x86dbg, ollydbg, sig scanning, memory comparisons, reverse engineering & brain with working functionalities such as the following:
eating
drinking
sleeping
physical exercise
good mental state
